### PR TITLE
Add Canadian and Canadian Multilangual layout

### PR DESCRIPTION
**Pull request by TheMMcOfficial**
Those keyboards are nor fully tested. They might have some ajustements to do in the future but the base is there.

Based on:
https://github.com/mame82/duckencoder.py/blob/master/resources/cm.properties
https://github.com/mame82/duckencoder.py/blob/master/resources/ca.properties

### CODE REVIEW

**Comment by mame82** [comment]
The `"name"` field in the header serves as selector in HIDScript, so I suggest changing the to 'CA' and 'CM'

**Comment by TheMMcOfficial** [comment]
I have done the change ;)

**Comment by mame82** [comment]
For testing you could add them to `/usr/local/P4wnP1/keymaps` on P4wnP1 A.L.O.A.

Suggested test is to type out the full ASCII character set from a HIDScript for both layouts.

If you find them working, I gonna merge and tag them for next version.

**Comment by TheMMcOfficial** [comment]
Ok thanks I will test them out when I will switch to P4wnP1 A.L.O.A. ... I still use the old version. I just need to take the time for it.

**Comment by TheMMcOfficial** [comment]
It's weird when I try to test my layout P4wnP1 always take the DE layout even if I told him to take the CM or th CA.

**Comment by mame82** [comment]
Blindly added the layouts to dev branch, because I can't test.

My test system is debian based, the layouts neither match `English (Canadian)` nor `French (Canadian), multilingual variant`.

Added it here for further testing:

https://github.com/mame82/P4wnP1_aloa/commit/37ad9236deac972d517eb457c99075551379efd6

Next release image has this included

**Comment by TheMMcOfficial** [comment]
The layouts are fix in this pull request: https://github.com/RoganDawes/P4wnP1_aloa/pull/270

Big thanks to @V0r-T3x for fixing the Canadian Multilingual!

**Pull request closed without merging**
